### ISSUE TITLE
Library Consolidation

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/organization#59]
Many libraries within `EthereumJS` have are in an unclear state regarding ownership and maintenance status. Here is a list taken from an internal chat discussion:
- [ ] [ethrpc](https://github.com/ethereumjs/ethrpc): Historically maintained externally by people from Augur, not much activity and not clear if actively maintained -> communicate with current part-time maintainers, move to Augur? GitHub org, take on within the JS team?
- [ ] [eth-bin-to-ops](https://github.com/ethereumjs/eth-bin-to-ops): Tiny, not touched very much (just 8 commits), likely in our own responsibility :-) -> usage status unclear, candidate for deprecation or monorepo consolidation, others (?)
- [ ] [node-ethash](https://github.com/ethereumjs/node-ethash): not actively maintained (last commit 2017), usage status absolutely unclear (no user within EthereumJS scope)
- [ ] [eth-query](https://github.com/ethereumjs/eth-query): tiny, not actively maintained, usage status unclear -> eventually ask Kumavis on this, otherwise also deprecation or monorepo
- [ ] [keythereum](https://github.com/ethereumjs/eth-query): also inititated from guys from Augur (tinybike), not actively maintained atm, I have also no good overview on the usage base, in doubt undermaintained though
- [ ] [fixed-bn.js](https://github.com/ethereumjs/fixed-bn.js) and [sharding](https://github.com/ethereumjs/sharding): (relatively new) experiments by @s1na
- [ ] [ethereumjs-icap](https://github.com/ethereumjs/ethereumjs-icap): in our responsibility, I think this is used (not sure though), a bit undermaintained and could need some more occasional updates (library not too big though)
- [ ] [helpeth](https://github.com/ethereumjs/helpeth): in our responsibility made by @axic, undermaintained since touches security related stuff, not completely sure about the usage status though
- [ ] [ethereumjs-blockstream](https://github.com/ethereumjs/ethereumjs-blockstream): also from Augur, similar to ethrpc
- [ ] [browser-builds](https://github.com/ethereumjs/browser-builds): several trials to revive not lasting, concept just doesn't work out
- [ ] [ethereumjs.github.io](https://github.com/ethereumjs/ethereumjs.github.io): some basic EthereumJS website on GitHub, I once gave this an update, not too accurate any more, can eventually be abandoned, no decision pressure there though
- [ ] [ethereumjs-units](https://github.com/ethereumjs/ethereumjs-units): similar to the icap library
- [ ] [ethereumjs-verified-contracts](https://github.com/ethereumjs/ethereum-verified-contracts): fanatid moved this to EthereumJS some time ago, this is not totally fitting to the EthereumJ scope and also not maintained, I would have a tendency to just ask him to take this back/somewhere else
- [ ] [ethereumjs-stub-rpc-server](https://github.com/ethereumjs/ethereumjs-stub-rpc-server): Augur, not maintained at all, deprecation/archive candidate?
- [ ] [geth.js](https://github.com/ethereumjs/geth.js): Augur, not maintained at all, deprecation/archive candidate?
- [ ] [eth-bin-to-method-ids](https://github.com/ethereumjs/eth-bin-to-method-ids): similar to eth-query (tiny, originally from Kumavis)

Over the next weeks and months we should go through these libraries, contact eventual maintainers, retake on maintenance ourself or deprecate or archive, this will be a case-by-case selection.

A library felt to be shifted to a clear status again should be checked in the list above. Sub issues created for single libraries along this meta issue should also be linked within the list.
